apiVersion: v1
appVersion: 2.4.48
description: Community developed LDAP software
engine: gotpl
home: https://www.openldap.org
icon: https://raw.githubusercontent.com/rdbox-intec/rdbox_app_market/master/icons/openldap.gif
keywords:
- ldap
- openldap
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: openldap
sources:
- https://github.com/kubernetes/charts
version: 1.2.5
