apiVersion: v1
appVersion: 0.5.2
description: Scrape metrics stored in prometheus format and push them to the Stackdriver
home: https://github.com/GoogleCloudPlatform/k8s-stackdriver/tree/master/prometheus-to-sd
keywords:
- prometheus
- stackdriver
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: prometheus-to-sd
version: 0.3.0
