apiVersion: v1
appVersion: v0.3.0
description: A k8s-spot-rescheduler Helm chart for Kubernetes
home: https://github.com/pusher/k8s-spot-rescheduler
keywords:
- spot
- rescheduler
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: k8s-spot-rescheduler
sources:
- https://github.com/pusher/k8s-spot-rescheduler
version: 0.4.4
