apiVersion: v1
appVersion: 0.4.10
description: CouchDB instance for Hyperledger Fabric (these charts are created by
  AID:Tech and are currently not directly associated with the Hyperledger project)
home: http://hyperledger-fabric.readthedocs.io
icon: https://raw.githubusercontent.com/rdbox-intec/rdbox_app_market/master/icons/hlf-couchdb.png
keywords:
- blockchain
- hyperledger
- fabric
- couchdb
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: hlf-couchdb
sources:
- https://github.com/hyperledger/fabric
version: 1.0.7
