# Default values for schema-registry-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: landoop/schema-registry-ui
  tag: 0.9.5
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  annotations: {}
  ## Limit load balancer source ips to list of CIDRs (where available)
  # loadBalancerSourceRanges: []

schemaRegistry:
  url: "http://localhost"
  port: 8081
  proxy: false
  allowGlobal: false
  allowTransitive: false
  allowDeletion: false
  readOnlyMode: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
#    - schema-registry-ui.local
    - schema-registry-ui.rdbox.lan
  tls:
    - hosts:
      - '*.rdbox.lan'
      secretName: rdbox-common-tls

resources: {}

nodeSelector:
  beta.kubernetes.io/arch: amd64
  beta.kubernetes.io/os: linux
  node.rdbox.com/location: hq

tolerations: []

affinity: {}
