apiVersion: v1
appVersion: 5.1.0
description: A reverse proxy that provides authentication with Google, Github or other
  providers
engine: gotpl
home: https://pusher.github.io/oauth2_proxy/
keywords:
- kubernetes
- oauth
- oauth2
- authentication
- google
- github
kubeVersion: '>=1.9.0-0'
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: oauth2-proxy
sources:
- https://github.com/pusher/oauth2_proxy
version: 3.2.2
