dependencies:
- condition: kubeStateMetrics.enabled
  name: kube-state-metrics
  repository: https://rdbox-intec.github.io/rdbox_app_market/bot-gen
  version: 2.8.*
- condition: nodeExporter.enabled
  name: prometheus-node-exporter
  repository: https://rdbox-intec.github.io/rdbox_app_market/bot-gen
  version: 1.10.*
- condition: grafana.enabled
  name: grafana
  repository: https://rdbox-intec.github.io/rdbox_app_market/bot-gen
  version: 5.3.*
