annotations:
  category: Database
apiVersion: v1
appVersion: 10.3.23
description: Fast, reliable, scalable, and easy to use open-source relational database
  system. MariaDB Server is intended for mission-critical, heavy-load production systems
  as well as for embedding into mass-deployed software. Highly available MariaDB cluster.
engine: gotpl
home: https://mariadb.org
icon: https://raw.githubusercontent.com/rdbox-intec/rdbox_app_market/master/icons/mariadb.png
keywords:
- mariadb
- mysql
- database
- sql
- prometheus
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: mariadb
sources:
- https://github.com/bitnami/bitnami-docker-mariadb
- https://github.com/prometheus/mysqld_exporter
version: 7.9.2
