apiVersion: v1
appVersion: 1.0.1
description: A Helm chart for prometheus node-exporter
home: https://github.com/prometheus/node_exporter/
keywords:
- node-exporter
- prometheus
- exporter
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: prometheus-node-exporter
sources:
- https://github.com/prometheus/node_exporter/
version: 1.11.1
