annotations:
  category: ProjectManagement
apiVersion: v1
appVersion: 2020.31.0
description: Collection of open source web applications that help software companies
  build better software.
engine: gotpl
home: https://www.phacility.com/phabricator/
icon: https://raw.githubusercontent.com/rdbox-intec/rdbox_app_market/master/icons/phabricator.png
keywords:
- phabricator
- http
- https
- web
- application
- collaboration
- project management
- bug tracking
- code review
- wiki
- git
- mercurial
- subversion
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: phabricator
sources:
- https://github.com/bitnami/bitnami-docker-phabricator
version: 9.1.14
