apiVersion: v1
appVersion: 20.7.0
description: GoCD is an open-source continuous delivery server to model and visualize
  complex workflows with ease.
home: https://www.gocd.org/
icon: https://raw.githubusercontent.com/rdbox-intec/rdbox_app_market/master/icons/gocd.png
keywords:
- gocd
- ci
- cd
- ci/cd
- continuous-integration
- continuous-delivery
- continuous-deployment
- continuous-testing
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: gocd
sources:
- https://github.com/gocd/gocd
version: 1.30.0
