apiVersion: v1
appVersion: 3.0.13
description: A Helm chart for Distributed OrientDB
home: https://orientdb.com
icon: https://raw.githubusercontent.com/rdbox-intec/rdbox_app_market/master/icons/orientdb.png
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: orientdb
version: 0.1.2
