annotations:
  category: Infrastructure
apiVersion: v1
appVersion: 2.6.0
description: Apache Kafka is a distributed streaming platform.
engine: gotpl
home: https://kafka.apache.org/
icon: https://raw.githubusercontent.com/rdbox-intec/rdbox_app_market/master/icons/kafka.png
keywords:
- kafka
- zookeeper
- streaming
- producer
- consumer
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: kafka
sources:
- https://github.com/bitnami/bitnami-docker-kafka
version: 11.8.2
