annotations:
  category: Infrastructure
apiVersion: v1
appVersion: v1.11.2
description: Kubeapps is a dashboard for your Kubernetes cluster that makes it easy
  to deploy and manage applications in your cluster using Helm
home: https://kubeapps.com
icon: https://raw.githubusercontent.com/rdbox-intec/rdbox_app_market/master/icons/kubeapps.png
keywords:
- helm
- dashboard
- service catalog
- deployment
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: kubeapps
sources:
- https://github.com/kubeapps/kubeapps
tillerVersion: '>=2.14.0'
version: 3.9.1
