apiVersion: v1
appVersion: 20.5.0
description: A Helm chart for kube-downscaler
home: https://github.com/hjacobs/kube-downscaler
keywords:
- k8s pods scheduler
- scheduled lifecycle
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: kube-downscaler
sources:
- https://github.com/hjacobs/kube-downscaler
version: 0.5.0
