apiVersion: v1
appVersion: 1.6.7
description: Unbound is a fast caching DNS resolver
home: https://www.unbound.net/
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: unbound
sources:
- http://unbound.nlnetlabs.nl/svn/
- https://github.com/Markbnj/unbound-docker
- https://github.com/kubernetes/contrib/tree/master/exec-healthz
version: 1.1.2
