replicaCount: 1

image:
  repository: alpine/socat
  tag: 1.0.3
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP

resources: {}

nodeSelector:
  beta.kubernetes.io/arch: amd64
  beta.kubernetes.io/os: linux
  node.rdbox.com/location: hq

tolerations: []

affinity: {}

podAnnotations: {}

tunnel:
  host: myhost
  port: 9999
