annotations:
  category: DeveloperTools
apiVersion: v1
appVersion: 4.3.0
description: Parse is a platform that enables users to add a scalable and powerful
  backend to launch a full-featured app for iOS, Android, JavaScript, Windows, Unity,
  and more.
engine: gotpl
home: https://parse.com/
icon: https://raw.githubusercontent.com/rdbox-intec/rdbox_app_market/master/icons/parse.png
keywords:
- parse
- backend
- serverless
- platform
- mbaas
- mobile
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: parse
sources:
- https://github.com/bitnami/bitnami-docker-parse
- https://github.com/bitnami/bitnami-docker-parse-dashboard
version: 11.0.4
