apiVersion: v1
appVersion: 0.12.0
description: Host your own Helm Chart Repository
home: https://github.com/helm/chartmuseum
icon: https://raw.githubusercontent.com/rdbox-intec/rdbox_app_market/master/icons/chartmuseum.png
keywords:
- chartmuseum
- helm
- charts repo
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: chartmuseum
version: 2.13.2
