# Default values for cassandra-reaper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: thelastpickle/cassandra-reaper
  tag: 1.3.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  labels: {}
  path: /
  hosts:
    - cassandra-reaper.rdbox.lan
  tls:
    - hosts:
      - '*.rdbox.lan'
      secretName: rdbox-common-tls
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  basicAuth:
    enabled: true
    name: ~
    # base64 encoded version of the basic auth file
    secret: ~

env: {}
resources: {}
nodeSelector:
  beta.kubernetes.io/arch: amd64
  beta.kubernetes.io/os: linux
  node.rdbox.com/location: hq
tolerations: []
affinity: {}
