annotations:
  category: E-Learning
apiVersion: v1
appVersion: 3.9.1
description: Moodle is a learning platform designed to provide educators, administrators
  and learners with a single robust, secure and integrated system to create personalised
  learning environments
engine: gotpl
home: http://www.moodle.org/
icon: https://raw.githubusercontent.com/rdbox-intec/rdbox_app_market/master/icons/moodle.png
keywords:
- moodle
- learning
- php
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: moodle
sources:
- https://github.com/bitnami/bitnami-docker-moodle
version: 8.1.1
