dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: https://rdbox-intec.github.io/rdbox_app_market/bot-gen
  version: 7.x.x
- name: common
  repository: https://rdbox-intec.github.io/rdbox_app_market/bot-gen
  version: 0.x.x
