apiVersion: v1
appVersion: v0.10.0
description: A Prometheus exporter for MongoDB metrics
home: https://github.com/percona/mongodb_exporter
keywords:
- exporter
- metrics
- mongodb
- prometheus
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: prometheus-mongodb-exporter
sources:
- https://github.com/percona/mongodb_exporter
version: 2.8.0
