annotations:
  category: Infrastructure
apiVersion: v1
appVersion: 1.6.6
description: Chart for Memcached
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/memcached
icon: https://raw.githubusercontent.com/rdbox-intec/rdbox_app_market/master/icons/memcached.png
keywords:
- memcached
- cache
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: memcached
sources:
- https://github.com/bitnami/bitnami-docker-memcached
- http://memcached.org/
version: 4.2.22
