annotations:
  category: Database
apiVersion: v1
appVersion: 11.9.0
description: Chart for PostgreSQL, an object-relational database management system
  (ORDBMS) with an emphasis on extensibility and on standards-compliance.
engine: gotpl
home: https://www.postgresql.org/
icon: https://raw.githubusercontent.com/rdbox-intec/rdbox_app_market/master/icons/postgresql.png
keywords:
- postgresql
- postgres
- database
- sql
- replication
- cluster
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: postgresql
sources:
- https://github.com/bitnami/bitnami-docker-postgresql
version: 9.3.3
