apiVersion: v1
appVersion: 0.3
description: A Helm chart for eventruter (https://github.com/heptiolabs/eventrouter)
home: https://github.com/heptiolabs/eventrouter
keywords:
- eventrouter
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: eventrouter
sources:
- https://github.com/heptiolabs/eventrouter
version: 0.3.0
