dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: https://rdbox-intec.github.io/rdbox_app_market/bot-gen
  version: 7.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: https://rdbox-intec.github.io/rdbox_app_market/bot-gen
  version: 8.x.x
