apiVersion: v1
appVersion: v0.68
description: A Helm chart for Karma - an UI for Prometheus Alertmanager
home: https://github.com/prymitive/karma
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: karma
sources:
- https://hub.docker.com/r/lmierzwa/karma/
- https://github.com/prymitive/karma
version: 1.5.2
