annotations:
  category: Infrastructure
apiVersion: v1
appVersion: 3.0.0
description: Spark is a fast and general-purpose cluster computing system.
home: https://spark.apache.org/
icon: https://raw.githubusercontent.com/rdbox-intec/rdbox_app_market/master/icons/spark.png
keywords:
- apache
- spark
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: spark
sources:
- https://github.com/bitnami/bitnami-docker-spark
version: 2.0.2
