apiVersion: v1
appVersion: 3.6
description: NoSQL document-oriented database that stores JSON-like documents with
  dynamic schemas, simplifying the integration of data in content-driven applications.
home: https://github.com/mongodb/mongo
icon: https://raw.githubusercontent.com/rdbox-intec/rdbox_app_market/master/icons/mongodb-replicaset.jpg
maintainers:
- email: info-rdbox@intec.co.jp
  name: RDBOX Project
name: mongodb-replicaset
sources:
- https://github.com/mongodb/mongo
- https://github.com/percona/mongodb_exporter
version: 3.17.1
